### ISSUE TITLE
Mod is not updated to current KubeJS

### ISSUE THREAD

**Issue by mbninjaguy** [impleri/player-skills#75] opened 2023-12-04 04:05 UTC
Minecraft Version
1.19.2

KubeJS Version
kubejs-forge-1902.6.2-build.42.jar

Rhino Version
rhino-forge-1902.2.2-build.280.jar

Architectury Version
architectury-6.5.85-forge.jar

Forge/Fabric Version
Forge-43.3.5

Describe your issue
I am trying to build a modpack, but this error keeps crashing the game. I was told that the issue is from this mod.

KubeJS has failed to load correctly
java.lang.NoClassDefFoundError:
dev/latvian/mods/kubejs/RegistryObjectBuilderTypes

[crash-2023-12-03_23.03.10-fml.txt](https://github.com/impleri/player-skills/files/13541791/crash-2023-12-03_23.03.10-fml.txt)

**Comment by impleri** [comment] 2023-12-12 04:04
Duplicate of #71

**Closed as completed by impleri** 2023-12-12 04:04 UTC
Labels: bug
